type: "diff_drive_controller/DiffDriveController"
publish_rate: 500

left_wheel: ['summitxls_front_left_wheel_joint', 'summitxls_back_left_wheel_joint']
right_wheel: ['summitxls_front_right_wheel_joint', 'summitxls_back_right_wheel_joint']

# Wheel separation and diameter. These are both optional.
# diff_drive_controller will attempt to read either one or both from the
# URDF if not specified as a parameter
wheel_separation : 0.470 #def 0.433
wheel_radius : 0.11 #def 0.0762

# Velocity commands timeout [s], default 0.5
cmd_vel_timeout: 0.25

# Odometry covariances for the encoder output of the robot. These values should
# be tuned to your robot's sample odometry data, but these values are a good place
# to start
pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

# Base frame_id
base_frame_id: summitxls_base_footprint
odom_frame_id: summitxls_odom
enable_odom_tf: true

# Velocity and acceleration limits for the robot
linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 3.0   # m/s
    has_acceleration_limits: true
    max_acceleration       : 6.0   # m/s^2
angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 6.0   # rad/s
    has_acceleration_limits: true
    max_acceleration       : 6.0   # rad/s^2
