panda_joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint1
  pid: {p: 10000,  d: 100, i: 10, i_clamp: 1}
  
panda_joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint2
  pid: {p: 10000,  d: 100, i: 10, i_clamp: 1}
  
panda_joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint3
  pid: {p: 10000,  d: 100, i: 10, i_clamp: 1}
  
panda_joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint4
  pid: {p: 10000,  d: 100, i: 10, i_clamp: 1}
  
panda_joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint5
  pid: {p: 50,  d: 100, i: 10, i_clamp: 1}
  
panda_joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint6
  pid: {p: 50,  d: 100, i: 10, i_clamp: 1}  
  
panda_joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint7
  pid: {p: 50,  d: 100, i: 10, i_clamp: 1}  
  
  
