joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

ur_position_controller:
 type: position_controllers/JointPositionController
 joints:
  - ur_shoulder_pan_joint
  - ur_shoulder_lift_joint
  - ur_elbow_joint
  - ur_wrist_1_joint
  - ur_wrist_2_joint
  - ur_wrist_3_joint
